
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating an sidebar entry for the modules section.
 * This sidebar has modules, overview, hardware, capstone, glossary, and resources.
 */
const sidebars: SidebarsConfig = {
  tutorial: [
    {
      type: 'doc',
      id: 'overview',
      label: 'Course Overview'
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules',
        },
      ],
      collapsed: false,
    },
    {
      type: 'doc',
      id: 'hardware/index',
      label: 'Hardware Requirements'
    },
    {
      type: 'doc',
      id: 'capstone/index',
      label: 'Capstone Project'
    },
    {
      type: 'doc',
      id: 'glossary',
      label: 'Glossary'
    },
    {
      type: 'doc',
      id: 'resources',
      label: 'Resources'
    }
  ],
};

export default sidebars;
